import { resolve, dirname } from 'path';
import { existsSync, writeFileSync, mkdirSync } from 'fs';
import { randomBytes } from 'crypto';
import { createInterface } from 'readline';
import { loadConfig } from '../../config/parser';
import { ChannelKit } from '../../index';
import { banner, c, ask, select } from '../helpers';
import { initCommand } from './init';
import { DEFAULT_AUTH_DIR } from '../../paths';
import { promptServiceInstall } from './service-install';

export async function startCommand(configPath: string, opts: { tunnel?: boolean; publicUrl?: string; remote?: string; remoteAuth?: string } = {}) {
  banner();

  const isRemote = !!opts.remote;

  // ── Remote mode: fetch config and auth from remote store ──
  if (isRemote) {
    console.log(c('magenta', `  📡 Remote mode: ${opts.remote}\n`));

    const { RemoteStore } = await import('../../core/remoteStore');
    const remoteStore = new RemoteStore({
      type: 'remote',
      endpoint: opts.remote!,
      auth_header: opts.remoteAuth,
    });

    // Fetch config
    const remoteYaml = await remoteStore.fetchConfig();
    if (remoteYaml) {
      const configDir = dirname(configPath);
      if (!existsSync(configDir)) mkdirSync(configDir, { recursive: true });
      writeFileSync(configPath, remoteYaml);
      console.log(c('green', '  ✅ Config loaded from remote\n'));
    } else {
      console.log(c('dim', '  No remote config found — using local config\n'));
    }

    // Fetch auth
    const authZip = await remoteStore.fetchAuth();
    if (authZip) {
      if (!existsSync(DEFAULT_AUTH_DIR)) mkdirSync(DEFAULT_AUTH_DIR, { recursive: true });
      await RemoteStore.unzipToDirectory(authZip, DEFAULT_AUTH_DIR);
      console.log(c('green', '  ✅ Auth loaded from remote\n'));
    } else {
      console.log(c('dim', '  No remote auth found — using local auth\n'));
    }
  }

  if (!existsSync(configPath)) {
    if (isRemote) {
      // Remote mode with no config — create minimal config and push to remote
      const secret = randomBytes(32).toString('base64url');
      const yaml = `# ChannelKit Configuration\n# Generated by channelkit\n\napi_secret: "${secret}"\n\nchannels: {}\n\nservices: {}\n`;

      const configDir = dirname(configPath);
      if (!existsSync(configDir)) mkdirSync(configDir, { recursive: true });
      if (!existsSync(DEFAULT_AUTH_DIR)) mkdirSync(DEFAULT_AUTH_DIR, { recursive: true });
      writeFileSync(configPath, yaml);

      // Push the new config to remote
      const { RemoteStore } = await import('../../core/remoteStore');
      const store = new RemoteStore({ type: 'remote', endpoint: opts.remote!, auth_header: opts.remoteAuth });
      await store.pushConfig(yaml);

      console.log(c('green', '\n  ✅ Config created and pushed to remote\n'));
      console.log(c('bright', '  🔐 Your dashboard secret:\n'));
      console.log(c('cyan', `     ${secret}\n`));
      console.log(c('dim', '  Copy this secret — you\'ll need it to log in to the dashboard.\n'));
    } else {
      console.log(c('dim', `  No config found at ${configPath}\n`));
      console.log(c('bright', '  First time? Let\'s set things up!\n'));

      const rl = createInterface({ input: process.stdin, output: process.stdout });
      const setupIdx = await select(rl, 'How would you like to configure ChannelKit?', [
        '🖥️  Dashboard — configure everything in the browser',
        '⌨️  CLI wizard — step-by-step setup in the terminal',
      ]);
      rl.close();

      if (setupIdx === 1) {
        await initCommand();
        return;
      }

      // Dashboard mode: create minimal config and start
      const secret = randomBytes(32).toString('base64url');
      const yaml = `# ChannelKit Configuration\n# Generated by channelkit\n\napi_secret: "${secret}"\n\nchannels: {}\n\nservices: {}\n`;

      const configDir = dirname(configPath);
      if (!existsSync(configDir)) mkdirSync(configDir, { recursive: true });
      if (!existsSync(DEFAULT_AUTH_DIR)) mkdirSync(DEFAULT_AUTH_DIR, { recursive: true });
      writeFileSync(configPath, yaml);

      console.log(c('green', '\n  ✅ Config created at ' + configPath + '\n'));
      console.log(c('bright', '  🔐 Your dashboard secret:\n'));
      console.log(c('cyan', `     ${secret}\n`));
      console.log(c('dim', '  Copy this secret — you\'ll need it to log in to the dashboard.\n'));
    }
  }

  console.log(c('dim', `  Loading config from ${configPath}\n`));

  let config;
  try {
    config = loadConfig(configPath, { validate: false });
  } catch (err: any) {
    console.error(c('yellow', `  ❌ Failed to load config: ${err.message}`));
    process.exit(1);
  }
  if (!config.channels) config.channels = {};
  if (!config.services) config.services = {};

  // In remote mode, inject the data_store config so ChannelKit syncs changes back
  if (isRemote) {
    config.data_store = {
      type: 'remote',
      endpoint: opts.remote!,
      ...(opts.remoteAuth && { auth_header: opts.remoteAuth }),
      sync_interval: config.data_store?.sync_interval || 30,
    };
  }

  if (opts.tunnel) {
    config.tunnel = { ...config.tunnel, provider: 'cloudflared' };
  }
  if (opts.publicUrl) {
    config.tunnel = { ...config.tunnel, public_url: opts.publicUrl };
  }

  const channelCount = Object.keys(config.channels).length;
  const serviceCount = Object.keys(config.services || {}).length;
  const routeCount = (config.routes || []).length;
  const totalBindings = serviceCount + routeCount;
  console.log(c('dim', `  ${channelCount} channel(s), ${totalBindings} service(s) configured\n`));

  const port = config.apiPort || 4000;

  if (config.tunnel) {
    if (config.tunnel.public_url) {
      console.log(c('magenta', `  📡 Using public URL: ${config.tunnel.public_url}\n`));
    } else if (config.tunnel.provider === 'cloudflared') {
      console.log(c('blue', `  💡 Your API port is ${port}. Point your tunnel to http://localhost:${port}\n`));
    }
  }

  const kit = new ChannelKit(config, configPath);

  process.on('SIGINT', () => {
    console.log(c('yellow', '\n  Shutting down...'));
    kit.stop().finally(() => {
      console.log(c('green', '  Done. Bye! 👋\n'));
      process.exit(0);
    });
    setTimeout(() => {
      console.log(c('dim', '  Force exit.'));
      process.exit(0);
    }, 3000);
  });

  await kit.start();

  // Open the dashboard in the default browser (only in interactive terminal, not daemon/background)
  if (process.stdin.isTTY) {
    const dashboardUrl = `http://localhost:${port}/dashboard`;
    const { exec: execCmd } = await import('child_process');
    execCmd(`open "${dashboardUrl}" 2>/dev/null || xdg-open "${dashboardUrl}" 2>/dev/null || start "${dashboardUrl}" 2>/dev/null`);
  }

  console.log();
  console.log(c('green', '  🚀 ChannelKit is running!\n'));

  // On first interactive run, offer to install as a system service
  if (process.stdin.isTTY) {
    await promptServiceInstall(configPath);
  }

  console.log(c('dim', '  Press Ctrl+C to stop\n'));
}
