#!/usr/bin/env node
import { Command } from 'commander';
import { resolve } from 'path';
import { existsSync, writeFileSync, mkdirSync } from 'fs';
import { createInterface } from 'readline';
import { loadConfig } from './config/parser';
import { ChannelKit } from './index';

const LOGO = `
  ╔═══════════════════════════════════════╗
  ║                                       ║
  ║     📱 ──┐                            ║
  ║     💬 ──┤──→ ChannelKit ──→ 🔗 App   ║
  ║     📞 ──┘                            ║
  ║                                       ║
  ║     Messaging ingress for your app    ║
  ║                                       ║
  ╚═══════════════════════════════════════╝
`;

const COLORS = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  dim: '\x1b[2m',
  cyan: '\x1b[36m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  magenta: '\x1b[35m',
  blue: '\x1b[34m',
  white: '\x1b[37m',
  gray: '\x1b[90m',
};

function c(color: keyof typeof COLORS, text: string): string {
  return `${COLORS[color]}${text}${COLORS.reset}`;
}

function banner() {
  console.log(c('cyan', LOGO));
  console.log(c('dim', `  v0.1.0\n`));
}

async function ask(rl: ReturnType<typeof createInterface>, question: string, defaultVal?: string): Promise<string> {
  const suffix = defaultVal ? c('dim', ` (${defaultVal})`) : '';
  return new Promise((resolve) => {
    rl.question(`  ${c('green', '?')} ${question}${suffix} `, (answer) => {
      resolve(answer.trim() || defaultVal || '');
    });
  });
}

async function select(rl: ReturnType<typeof createInterface>, question: string, options: string[]): Promise<number> {
  console.log(`\n  ${c('green', '?')} ${question}\n`);
  options.forEach((opt, i) => {
    console.log(`    ${c('cyan', `${i + 1})`)} ${opt}`);
  });
  console.log();
  
  while (true) {
    const answer = await ask(rl, `Choose ${c('dim', `[1-${options.length}]`)}:`);
    const num = parseInt(answer);
    if (num >= 1 && num <= options.length) return num - 1;
    console.log(c('yellow', '    Please enter a valid number'));
  }
}

async function initCommand() {
  banner();
  console.log(c('bright', '  Welcome to ChannelKit! Let\'s get you set up.\n'));

  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  try {
    // Step 1: Channel selection
    const channelIdx = await select(rl, 'Which channel do you want to connect?', [
      '📱 WhatsApp — connect with your phone number',
      '💬 Telegram — create a bot',
      '📧 Email — connect IMAP/SMTP',
    ]);

    const channels: Record<string, any> = {};
    const routes: any[] = [];

    if (channelIdx === 0) {
      // WhatsApp
      console.log();
      const number = await ask(rl, 'Your WhatsApp phone number (with country code):', '+972...');
      
      const modeIdx = await select(rl, 'How will you use this channel?', [
        '👤 Personal — route messages from groups on your number',
        '🏢 Service — dedicated number, every incoming message routed',
      ]);

      channels['whatsapp'] = {
        type: 'whatsapp',
        number: number,
        mode: modeIdx === 0 ? 'groups' : 'direct',
      };

      routes.push({
        channel: 'whatsapp',
        match: '*',
        webhook: '',
      });

    } else if (channelIdx === 1) {
      // Telegram
      console.log();
      console.log(c('dim', '  Create a bot via @BotFather on Telegram and paste the token.\n'));
      const token = await ask(rl, 'Bot token:');

      channels['telegram'] = {
        type: 'telegram',
        bot_token: token,
      };

      routes.push({
        channel: 'telegram',
        match: '*',
        webhook: '',
      });

    } else {
      // Email
      console.log();
      const address = await ask(rl, 'Email address:', 'support@myapp.com');
      const imap = await ask(rl, 'IMAP server:', 'imap.gmail.com');

      channels['email'] = {
        type: 'email',
        address,
        imap,
      };

      routes.push({
        channel: 'email',
        match: '*',
        webhook: '',
      });
    }

    // Step 2: Webhook
    console.log();
    const webhook = await ask(rl, 'Where should messages be sent? (webhook URL):', 'http://localhost:3000/api/chat');
    routes.forEach(r => r.webhook = webhook);

    // Step 3: Generate config
    console.log();
    const configPath = await ask(rl, 'Config file path:', 'config.yaml');

    // Build YAML manually for nice formatting
    let yaml = `# ChannelKit Configuration\n# Generated by channelkit init\n\nchannels:\n`;
    
    for (const [name, cfg] of Object.entries(channels)) {
      yaml += `  ${name}:\n`;
      for (const [key, value] of Object.entries(cfg as any)) {
        yaml += `    ${key}: "${value}"\n`;
      }
    }

    yaml += `\nroutes:\n`;
    for (const route of routes) {
      yaml += `  - channel: ${route.channel}\n`;
      yaml += `    match: "${route.match}"\n`;
      yaml += `    webhook: "${route.webhook}"\n`;
    }

    // Write config
    const fullPath = resolve(configPath);
    if (existsSync(fullPath)) {
      const overwrite = await ask(rl, `${configPath} already exists. Overwrite? (y/N):`, 'N');
      if (overwrite.toLowerCase() !== 'y') {
        console.log(c('yellow', '\n  Aborted. Config not written.\n'));
        rl.close();
        return;
      }
    }

    writeFileSync(fullPath, yaml);

    // Create auth directory
    if (!existsSync('auth')) {
      mkdirSync('auth');
    }

    // Done!
    console.log();
    console.log(c('green', '  ╔═══════════════════════════════════════╗'));
    console.log(c('green', '  ║                                       ║'));
    console.log(c('green', '  ║   ✅ Config created successfully!     ║'));
    console.log(c('green', '  ║                                       ║'));
    console.log(c('green', '  ╚═══════════════════════════════════════╝'));
    console.log();
    console.log(c('white', '  Next steps:\n'));
    console.log(c('dim', `    1. Make sure your webhook is running at ${webhook}`));
    console.log(c('dim', '    2. Start ChannelKit:\n'));
    console.log(c('cyan', '       npx channelkit start'));
    console.log();
    
    if (channels['whatsapp']) {
      console.log(c('dim', '    3. Scan the QR code with WhatsApp'));
      console.log(c('dim', '       (Settings → Linked Devices → Link a Device)\n'));
    }

    // Ask to start now
    const startNow = await ask(rl, 'Start ChannelKit now? (Y/n):', 'Y');
    rl.close();

    if (startNow.toLowerCase() !== 'n') {
      console.log();
      await startCommand(fullPath);
    }

  } catch (err) {
    rl.close();
    throw err;
  }
}

async function startCommand(configPath: string) {
  banner();

  console.log(c('dim', `  Loading config from ${configPath}\n`));

  let config;
  try {
    config = loadConfig(configPath);
  } catch (err: any) {
    console.error(c('yellow', `  ❌ Failed to load config: ${err.message}`));
    process.exit(1);
  }

  const channelCount = Object.keys(config.channels).length;
  const routeCount = config.routes.length;
  console.log(c('dim', `  ${channelCount} channel(s), ${routeCount} route(s) configured\n`));

  const kit = new ChannelKit(config);

  process.on('SIGINT', async () => {
    console.log(c('yellow', '\n  Shutting down gracefully...'));
    await kit.stop();
    console.log(c('green', '  Done. Bye! 👋\n'));
    process.exit(0);
  });

  await kit.start();
  
  console.log();
  console.log(c('green', '  🚀 ChannelKit is running!\n'));
  console.log(c('dim', '  Press Ctrl+C to stop\n'));
}

// CLI setup
const program = new Command();

program
  .name('channelkit')
  .description('Messaging ingress for your app')
  .version('0.1.0');

program
  .command('init')
  .description('Set up ChannelKit interactively')
  .action(async () => {
    try {
      await initCommand();
    } catch (err: any) {
      console.error(c('yellow', `\n  ❌ ${err.message}\n`));
      process.exit(1);
    }
  });

program
  .command('start')
  .description('Start ChannelKit')
  .option('-c, --config <path>', 'Path to config file', 'config.yaml')
  .action(async (opts) => {
    const configPath = resolve(opts.config);
    await startCommand(configPath);
  });

// Service management commands
const service = program
  .command('service')
  .description('Manage onboarding services');

service
  .command('add')
  .description('Add a new service interactively')
  .option('-c, --config <path>', 'Path to config file', 'config.yaml')
  .action(async (opts) => {
    const configPath = resolve(opts.config);
    if (!existsSync(configPath)) {
      console.error(c('yellow', `\n  ❌ Config file not found: ${configPath}\n  Run 'channelkit init' first.\n`));
      process.exit(1);
    }

    const { loadConfig, saveConfig } = await import('./config/parser');
    const config = loadConfig(configPath);

    const rl = createInterface({ input: process.stdin, output: process.stdout });

    try {
      console.log(c('cyan', '\n  📦 Add a new service\n'));

      const name = await ask(rl, 'Service name:');
      if (!name) { rl.close(); return; }

      const suggestedCode = name.toUpperCase().replace(/[^A-Z0-9]/g, '');
      const code = await ask(rl, 'Magic code:', suggestedCode);

      const webhook = await ask(rl, 'Webhook URL:', 'http://localhost:3000/api/chat');

      if (!config.onboarding) config.onboarding = { codes: [] };
      if (!config.onboarding.codes) config.onboarding.codes = [];

      // Check for duplicate code
      const existing = config.onboarding.codes.find(c => c.code.toUpperCase() === code.toUpperCase());
      if (existing) {
        console.log(c('yellow', `\n  ⚠️  Code "${code}" already exists for service "${existing.name}"\n`));
        rl.close();
        return;
      }

      config.onboarding.codes.push({ code: code.toUpperCase(), name, webhook });
      saveConfig(configPath, config);

      // Find WhatsApp number for share link
      const waChannel = Object.values(config.channels).find((ch: any) => ch.type === 'whatsapp') as any;
      const number = waChannel?.number?.replace(/[^0-9]/g, '') || '';

      console.log(c('green', `\n  ✅ Service "${name}" added!\n`));
      console.log(c('dim', `  Code:    ${code.toUpperCase()}`));
      console.log(c('dim', `  Webhook: ${webhook}`));
      if (number) {
        console.log(c('cyan', `\n  📱 Share link: https://wa.me/${number}?text=${encodeURIComponent(code.toUpperCase())}\n`));
      }
    } finally {
      rl.close();
    }
  });

service
  .command('list')
  .description('List all configured services')
  .option('-c, --config <path>', 'Path to config file', 'config.yaml')
  .action(async (opts) => {
    const configPath = resolve(opts.config);
    if (!existsSync(configPath)) {
      console.error(c('yellow', `\n  ❌ Config file not found: ${configPath}\n`));
      process.exit(1);
    }

    const { loadConfig } = await import('./config/parser');
    const config = loadConfig(configPath);
    const codes = config.onboarding?.codes || [];

    if (codes.length === 0) {
      console.log(c('dim', '\n  No services configured. Run `channelkit service add` to add one.\n'));
      return;
    }

    const waChannel = Object.values(config.channels).find((ch: any) => ch.type === 'whatsapp') as any;
    const number = waChannel?.number?.replace(/[^0-9]/g, '') || '';

    console.log(c('cyan', '\n  📦 Configured Services\n'));
    for (const svc of codes) {
      console.log(c('bright', `  ${svc.name}`));
      console.log(c('dim', `    Code:    ${svc.code}`));
      console.log(c('dim', `    Webhook: ${svc.webhook}`));
      if (number) {
        console.log(c('dim', `    Share:   https://wa.me/${number}?text=${encodeURIComponent(svc.code)}`));
      }
      console.log();
    }
  });

service
  .command('remove <name>')
  .description('Remove a service by name')
  .option('-c, --config <path>', 'Path to config file', 'config.yaml')
  .action(async (name, opts) => {
    const configPath = resolve(opts.config);
    if (!existsSync(configPath)) {
      console.error(c('yellow', `\n  ❌ Config file not found: ${configPath}\n`));
      process.exit(1);
    }

    const { loadConfig, saveConfig } = await import('./config/parser');
    const config = loadConfig(configPath);
    const codes = config.onboarding?.codes || [];

    const idx = codes.findIndex(c => c.name.toLowerCase() === name.toLowerCase());
    if (idx === -1) {
      console.error(c('yellow', `\n  ❌ Service "${name}" not found.\n`));
      process.exit(1);
    }

    const removed = codes.splice(idx, 1)[0];
    if (!config.onboarding) config.onboarding = { codes: [] };
    config.onboarding.codes = codes;
    saveConfig(configPath, config);

    console.log(c('green', `\n  ✅ Removed service "${removed.name}" (code: ${removed.code})\n`));
  });

program.parse();
