#!/usr/bin/env node
import { Command } from 'commander';
import { resolve } from 'path';
import { existsSync, writeFileSync, mkdirSync } from 'fs';
import { createInterface } from 'readline';
import { loadConfig } from './config/parser';
import { ChannelKit } from './index';

const LOGO = `
  ╔═══════════════════════════════════════╗
  ║                                       ║
  ║     📱 ──┐                            ║
  ║     💬 ──┤──→ ChannelKit ──→ 🔗 App   ║
  ║     📞 ──┘                            ║
  ║                                       ║
  ║     Messaging ingress for your app    ║
  ║                                       ║
  ╚═══════════════════════════════════════╝
`;

const COLORS = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  dim: '\x1b[2m',
  cyan: '\x1b[36m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  magenta: '\x1b[35m',
  blue: '\x1b[34m',
  white: '\x1b[37m',
  gray: '\x1b[90m',
};

function c(color: keyof typeof COLORS, text: string): string {
  return `${COLORS[color]}${text}${COLORS.reset}`;
}

function banner() {
  console.log(c('cyan', LOGO));
  console.log(c('dim', `  v0.1.0\n`));
}

async function ask(rl: ReturnType<typeof createInterface>, question: string, defaultVal?: string): Promise<string> {
  const suffix = defaultVal ? c('dim', ` (${defaultVal})`) : '';
  return new Promise((resolve) => {
    rl.question(`  ${c('green', '?')} ${question}${suffix} `, (answer) => {
      resolve(answer.trim() || defaultVal || '');
    });
  });
}

async function select(rl: ReturnType<typeof createInterface>, question: string, options: string[]): Promise<number> {
  console.log(`\n  ${c('green', '?')} ${question}\n`);
  options.forEach((opt, i) => {
    console.log(`    ${c('cyan', `${i + 1})`)} ${opt}`);
  });
  console.log();
  
  while (true) {
    const answer = await ask(rl, `Choose ${c('dim', `[1-${options.length}]`)}:`);
    const num = parseInt(answer);
    if (num >= 1 && num <= options.length) return num - 1;
    console.log(c('yellow', '    Please enter a valid number'));
  }
}

async function initCommand() {
  banner();
  console.log(c('bright', '  Welcome to ChannelKit! Let\'s get you set up.\n'));

  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  try {
    // Step 1: Channel selection
    const channelIdx = await select(rl, 'Which channel do you want to connect?', [
      '📱 WhatsApp — connect with your phone number',
      '💬 Telegram — create a bot',
      '📧 Email — connect IMAP/SMTP',
    ]);

    const channels: Record<string, any> = {};
    const routes: any[] = [];

    if (channelIdx === 0) {
      // WhatsApp
      console.log();
      const number = await ask(rl, 'Your WhatsApp phone number (with country code):', '+972...');
      
      const modeIdx = await select(rl, 'How will you use this channel?', [
        '👤 Personal — route messages from groups on your number',
        '🏢 Service — dedicated number, every incoming message routed',
      ]);

      channels['whatsapp'] = {
        type: 'whatsapp',
        number: number,
        mode: modeIdx === 0 ? 'groups' : 'direct',
      };

      routes.push({
        channel: 'whatsapp',
        match: '*',
        webhook: '',
      });

    } else if (channelIdx === 1) {
      // Telegram
      console.log();
      console.log(c('dim', '  Create a bot via @BotFather on Telegram and paste the token.\n'));
      const token = await ask(rl, 'Bot token:');

      channels['telegram'] = {
        type: 'telegram',
        bot_token: token,
      };

      routes.push({
        channel: 'telegram',
        match: '*',
        webhook: '',
      });

    } else {
      // Email
      console.log();
      const address = await ask(rl, 'Email address:', 'support@myapp.com');
      const imap = await ask(rl, 'IMAP server:', 'imap.gmail.com');

      channels['email'] = {
        type: 'email',
        address,
        imap,
      };

      routes.push({
        channel: 'email',
        match: '*',
        webhook: '',
      });
    }

    // Step 2: Webhook
    console.log();
    const webhook = await ask(rl, 'Where should messages be sent? (webhook URL):', 'http://localhost:3000/api/chat');
    routes.forEach(r => r.webhook = webhook);

    // Step 3: Generate config
    console.log();
    const configPath = await ask(rl, 'Config file path:', 'config.yaml');

    // Build YAML manually for nice formatting
    let yaml = `# ChannelKit Configuration\n# Generated by channelkit init\n\nchannels:\n`;
    
    for (const [name, cfg] of Object.entries(channels)) {
      yaml += `  ${name}:\n`;
      for (const [key, value] of Object.entries(cfg as any)) {
        yaml += `    ${key}: "${value}"\n`;
      }
    }

    yaml += `\nroutes:\n`;
    for (const route of routes) {
      yaml += `  - channel: ${route.channel}\n`;
      yaml += `    match: "${route.match}"\n`;
      yaml += `    webhook: "${route.webhook}"\n`;
    }

    // Write config
    const fullPath = resolve(configPath);
    if (existsSync(fullPath)) {
      const overwrite = await ask(rl, `${configPath} already exists. Overwrite? (y/N):`, 'N');
      if (overwrite.toLowerCase() !== 'y') {
        console.log(c('yellow', '\n  Aborted. Config not written.\n'));
        rl.close();
        return;
      }
    }

    writeFileSync(fullPath, yaml);

    // Create auth directory
    if (!existsSync('auth')) {
      mkdirSync('auth');
    }

    // Done!
    console.log();
    console.log(c('green', '  ╔═══════════════════════════════════════╗'));
    console.log(c('green', '  ║                                       ║'));
    console.log(c('green', '  ║   ✅ Config created successfully!     ║'));
    console.log(c('green', '  ║                                       ║'));
    console.log(c('green', '  ╚═══════════════════════════════════════╝'));
    console.log();
    console.log(c('white', '  Next steps:\n'));
    console.log(c('dim', `    1. Make sure your webhook is running at ${webhook}`));
    console.log(c('dim', '    2. Start ChannelKit:\n'));
    console.log(c('cyan', '       npx channelkit start'));
    console.log();
    
    if (channels['whatsapp']) {
      console.log(c('dim', '    3. Scan the QR code with WhatsApp'));
      console.log(c('dim', '       (Settings → Linked Devices → Link a Device)\n'));
    }

    // Ask to start now
    const startNow = await ask(rl, 'Start ChannelKit now? (Y/n):', 'Y');
    rl.close();

    if (startNow.toLowerCase() !== 'n') {
      console.log();
      await startCommand(fullPath);
    }

  } catch (err) {
    rl.close();
    throw err;
  }
}

async function startCommand(configPath: string) {
  banner();

  console.log(c('dim', `  Loading config from ${configPath}\n`));

  let config;
  try {
    config = loadConfig(configPath);
  } catch (err: any) {
    console.error(c('yellow', `  ❌ Failed to load config: ${err.message}`));
    process.exit(1);
  }

  const channelCount = Object.keys(config.channels).length;
  const routeCount = config.routes.length;
  console.log(c('dim', `  ${channelCount} channel(s), ${routeCount} route(s) configured\n`));

  const kit = new ChannelKit(config);

  process.on('SIGINT', async () => {
    console.log(c('yellow', '\n  Shutting down gracefully...'));
    await kit.stop();
    console.log(c('green', '  Done. Bye! 👋\n'));
    process.exit(0);
  });

  await kit.start();
  
  console.log();
  console.log(c('green', '  🚀 ChannelKit is running!\n'));
  console.log(c('dim', '  Press Ctrl+C to stop\n'));
}

// CLI setup
const program = new Command();

program
  .name('channelkit')
  .description('Messaging ingress for your app')
  .version('0.1.0');

program
  .command('init')
  .description('Set up ChannelKit interactively')
  .action(async () => {
    try {
      await initCommand();
    } catch (err: any) {
      console.error(c('yellow', `\n  ❌ ${err.message}\n`));
      process.exit(1);
    }
  });

program
  .command('start')
  .description('Start ChannelKit')
  .option('-c, --config <path>', 'Path to config file', 'config.yaml')
  .action(async (opts) => {
    const configPath = resolve(opts.config);
    await startCommand(configPath);
  });

program.parse();
